#!/usr/bin/env bash
# install nginx and configure it on remote server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
