#!/usr/bin/env bash
# Update system
sudo apt-get update
# Install HAProxy
sudo apt-get -y install haproxy
# Configure
config_string=\
"
frontend server-frontend
    bind *:80
    mode http
    default_backend server_backend

backend server_backend
    balance roundrobin
    server 281285-web-01 52.86.86.114:80 check
    server 281285-web-02 18.210.33.122:80 check
"
echo "$config_string" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy init script
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
