#!/usr/bin/env bash
# configure server to listen on port 80 of all active IPv4 servers

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
