#!/usr/bin/env bash
# Display 1-100 in list format
# Display "FizzBuzz" if multiple of 3 and 5
# Display "Fizz" if multiple of 3
# Display "Buzz" if multiple of 5

for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
