#!/usr/bin/env bash
# Tell a story of contents of `/etc/passwd` file

while IFS=':' read -r usernm psswd usrid grpid info home shell;
do
	echo "The user $usernm is part of the $grpid gang,"\
	"lives in $home and rides $shell."\
	"$usrid's place is protected by the passcode $psswd,"\
	"more info about the user here: $info"
done < "/etc/passwd"
