#!/usr/bin/env bash
# Parses Apache log files grouped by IP and HTTP status code
# Display number of occurrences, IP, and HTTP status code of each log, sorted 

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
