#!/usr/bin/env bash
# Display nrs 1-20 and
# 4 = "bad luck from China"
# 9 = "bad luck from Japan"
# 17 = "bad luck from Italy"

i=1

while [ $i -le 20 ];
do
	echo "$i"
	case "$i" in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	((i++))
done
